FROM centos:7
ARG KUBECTL_VERSION="v1.23.6"
RUN yum update -y
RUN yum install -y etcd
RUN yum install -y bind-utils
RUN yum install -y epel-release
RUN yum install -y jq
RUN yum install -y wget

RUN mkdir -p /usr/local/bin
COPY usr/local/bin /usr/local/bin
# install kubectl
RUN wget -q -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
    && chmod +x /usr/local/bin/kubectl 


RUN chmod +x /usr/local/bin/*
CMD /bin/bash -c -- "while true; do sleep 30; done;" 

